### ISSUE TITLE
Zero Termination displayed as space

### ISSUE THREAD

**Issue by smarkwardt** [COVESA/dlt-viewer#376]
Wrong Space in decoded Payload when an argument of type string is followed by an argument of an other type.
![dlt_001](https://github.com/COVESA/dlt-viewer/assets/708975/85153f94-5b6e-49f1-9eb7-9c8080cd8444)

**Comment by alexmucde** [comment]
@smarkwardt Please tell me to which plugin etc. this issue is related? Is this an open source plugin?

**Comment by smarkwardt** [comment]
@alexmucde 
I think it's a basic functionality of the dlt-viewer and not a plugin.

The spaces are incorrectly displayed by the dlt viewer.

````
DLT_LOG(mycontext, DLT_LOG_INFO, DLT_STRING("val: '"), DLT_INT(1), DLT_STRING("'"));
DLT_LOG(mycontext, DLT_LOG_INFO, DLT_STRING("aaa"), DLT_STRING("bbb"));
````

![Screenshot 2023-09-18 153300](https://github.com/COVESA/dlt-viewer/assets/708975/29531174-a309-4176-9272-486224f250bb)

From my point of view, it is unfavorable because you have to take the unnecessary spaces in the filter query into account.

**Comment by alexmucde** [comment]
Thanks for the detailed explanation. Now i understand better your issue.
Arguments of a DLT messages are separated by a space, when converted to ASCII.
This feature is implemented since the beginning of the DLT Viewer development.
The users of the DLT Viewer are used to this feature.
Other logging frameworks like Qt Logging behave the same.
